### PR TITLE
reset text area width

### PR DESCRIPTION
**Pull request by Erkajp**
my eye textarea is too width

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, could you send a before/after screenshot so I can see the issue? If this in Firefox or Chrome?

**Comment by Erkajp** [comment]
sorry i just try html direcly in localhost server. if try in add on firefox how to show option menu?

**Comment by danielnaber** [comment]
Go to `about:addons`, each add-on has an options button.

**Comment by Erkajp** [comment]
after load manifest or options.html, add-on always only “LanguageTool - Grammar and Style Checker", option button in list add-on in ``about:debugging#addons`` or in the add-on?

**Comment by danielnaber** [comment]
I see the option button at `about:addons`, next to the deactivate and remove button. It might not be named "options" though, as I'm using the German version. Also, this is true for the regularly installed add-on from https://addons.mozilla.org/de/firefox/addon/languagetool/.

**Comment by Erkajp** [comment]
oh i see sorry, my mistake.
i really intersting to contributing, can you suggest what i need to do which easy?

**Comment by danielnaber** [comment]
These issues seem to be good starting points: #17 #60 #69

**Comment by Erkajp** [comment]
about #17 i can detect textcontent in email signature, but i can't to ignore

**Comment by Erkajp** [comment]
@danielnaber  option 2: i think if user click email signature will can't selection
but i don't know where to add action in addon button

**Pull request closed without merging**
