### PR TITLE
fixed issue #60 (Keep manually selected language)

### PR DESCRIPTION
**Pull request by dk-extdev**
fixed issue #60

### CODE REVIEW

**Comment by danielnaber** [comment]
I think we could just save the state in a variable, without using storage. It's enough if we keep the user's selection while they are on the page. No need to store it for the next visit (actually that might cause bugs, if they use a different language next time). Isn't `popup.js` per page automatically? Then having a variable there would be fine.

**Comment by dk-extdev** [comment]
state can not be saved without using storage.
i think current save state function working correctly.
it didn't store state for the next visit. it only show saved state on same url popup.
lf user select a language on https://languagetool.org/, extension show selected language only on https://languagetool.org/. it didn't show selected language on like https://languagetool.org/development/
only selected language save for current url. so didn't conflict.
i hope you check after merge or install with my branch source code.

**Comment by danielnaber** [comment]
I see - but can't we store state in `contentscript.js`? That way, it would automatically live only until the page is left(?) which is what we want in this case. I've just checked your change and the problem is that the state is stored even after a reload.

**Comment by dk-extdev** [comment]
K. i see what do you want. let me update function after fix #190.

**Comment by danielnaber** [comment]
I got an email about your upwork account being blocked, please fix that first, as otherwise I won't be able to pay you.

**Comment by danielnaber** [comment]
There's another bug, `tabs`in `currentActiveUrl = tabs[0].url;` is sometimes(?) not defined. As you're changing the logic anyway, I'll just roll back this PR commit.

**Pull request merged**
