### PR TITLE
Update build tools to work only within project directory

### PR DESCRIPTION
**Pull request by bekicot**
The previous build tools only works on certain environtment. With this changes, the build process is done within project directory.

Also added dist/ folder for the latest stable release.

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, I've manually applied this, as the RP contained the contents of the `dist` and I don't think that was intended.

**Comment by bekicot** [comment]
@danielnaber Actually that was intended ;) Just like any other javascript libs.

**Comment by danielnaber** [comment]
Well, this is intended as an add-on, not as a library. Anyway, as "building" means nothing more than zipping the files, I think we don't need to add the resulting ZIPs.

**Comment by bekicot** [comment]
@danielnaber Actually, i'm creating the script that create crx files out of the zipped files. But as you think zip is enough. I'm halting the coding now ;). 👍

**Pull request closed without merging**
