### PR TITLE
add indonesian i18n

### PR DESCRIPTION
**Pull request by Erkajp**

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks for your contribution, but we only add languages to the user interface that LT also supports as input languages, i.e. languages it can check. Plus, we use a translation tool and don't work on the files directly. If you'd like to add support for Indonesian to LT (which is a major project), please check out http://wiki.languagetool.org/development-overview

**Comment by Erkajp** [comment]
oops sorry

**Comment by Erkajp** [comment]
i can't found indonesia in Available languages

**Comment by danielnaber** [comment]
Yes, that's what I was saying: LanguageTool doesn't support Indonesian yet until someone adds support for it.

**Pull request closed without merging**
