### PR TITLE
Create package.json

### PR DESCRIPTION
**Pull request by sanAkdam**
I added `package.json` to make other contributors easier to install all dependency and test the addon.

### CODE REVIEW

**Comment by danielnaber** [comment]
Thanks, how exactly will this be used, i.e. what exactly does it do?

**Comment by sanAkdam** [comment]
At first, I don't know how to test this, so I read the documentation and install `mocha` and run it. but still error can't find module `assert`, after install, it's still error can't find module `mock-browser`.

It would be much simpler to add package.json, so [npm](https://www.npmjs.com) will look at the file and install all dependency defined. to test the file just run `npm test`.

**Comment by danielnaber** [comment]
mocha currently doesn't wor

**Comment by sanAkdam** [comment]
did you run `npm install` and `npm test`?

**Comment by danielnaber** [comment]
Sorry, made a mistake when testing, now it's working.

**Comment by sanAkdam** [comment]
oke

**Pull request merged**
