### PR TITLE
Fixed unescaped '{' in format spec

### PR DESCRIPTION
**Pull request by edawine**
Escape '{' that is not supposed to be in format

### CODE REVIEW

**Comment by edawine** [comment]
@danielnaber Sorry about that, it should be fixed now.

**Comment by danielnaber** [comment]
There's still some kind of issue as the translations don't actually get replaced anymore. Sorry, this is difficult to test for you. I'm using `updateLocales.bash` but that relies on my personal password...

**Comment by edawine** [comment]
Can you tell me at which lines it should be a translation?

**Comment by danielnaber** [comment]
I've fixed the issue, see my latest commit.

**Comment by edawine** [comment]
@danielnaber OK, I'm sorry for the trouble.

**Pull request merged**
